gym_id: "SafetyPointReachAvoidResetGoalCurriculum5-v0"
seed: 0
total_timesteps: 1000000
torch_deterministic: true
cuda: true
capture_video: true
capture_video_ep_interval: 100
camera_id: null
camera_name: "fixednear"
num_envs: 1
clip_action: false
normalize_observation: false
normalize_reward: false
save_model: true
save_model_ep_interval: 100
env_seed: null
