gym_id: "SafetyPointReachAvoidLowFreqCurriculum5-v0"
seed: 0
total_eps: 1000
torch_deterministic: true
cuda: true
capture_video: true
capture_video_ep_interval: 100
camera_id: null
camera_name: "fixednear"
num_envs: 1
clip_action: false
normalize_observation: false
normalize_reward: false
save_db: true
save_db_ep_interval: 100
policy_path: "policies/base_policy_low_freq.pt"
load_db: false
load_db_path: "databases/task_policy_db_low_freq.pkl"
control_rng: true
env_seed: null
