gym_id: "HalfCheetah-v4"
seed: 0
total_timesteps: 501000
torch_deterministic: true
cuda: true
capture_video: true
capture_video_ep_interval: 100
num_envs: 1
clip_action: true
normalize_observation: true
normalize_reward: true
save_model: true
save_model_ep_interval: 100
