gym_id: "SafetyPointReachAvoidLowFreqResetGoalCurriculum5-v0"
seed: 0
total_timesteps: 20100
torch_deterministic: true
cuda: true
capture_video: true
capture_video_ep_interval: 100
num_envs: 1
clip_action: false
normalize_observation: false
normalize_reward: false
save_model: true
save_model_ep_interval: 100
env_seed: 0
