gym_id: "HalfCheetah-v4"
seed: 0
total_timesteps: 201000
torch_deterministic: true
cuda: true
capture_video: true
capture_video_ep_interval: 100
num_envs: 1
preprocess_envs: false
save_model: true
save_model_ep_interval: 100
