gym_id: "SafetyPointReachAvoidCurriculum5-v0"
seed: 0
total_eps: 1000
torch_deterministic: true
cuda: true
capture_video: true
capture_video_ep_interval: 100
num_envs: 1
clip_action: false
normalize_observation: false
normalize_reward: false
save_db: true
save_db_ep_interval: 100
policy_path: "policies/base_policy.pt"
load_db: false
load_db_path: "databases/task_policy_db.pkl"
control_rng: true
fixed_env: false
env_seed: 0
