lr: 3.0e-4
anneal_lr: true
adam_epsilon: 1.0e-8
num_steps: 2048
gae: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 32
update_epochs: 10
norm_adv: true
clip_coef: 0.2
clip_vloss: false
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
state_dependent_std: false
