policy_lr: 3.0e-4
q_lr: 1.0e-3
adam_epsilon: 1.0e-8
gamma: 0.99
buffer_size: 100000
batch_size: 256
burn_in: 5000
ent_coeff: 0.2
autotune: true
policy_freq: 2
targ_net_freq: 1
tau: 0.005
targ_ent_coeff: -0.41
per: false
per_alpha: 0.6
per_beta_start: 0.4
per_beta_end: 1.0
curriculum: false
curriculum_levels: [1, 2, 3, 4, 5]
curriculum_thresholds: [0.95, 0.95, 0.95, 0.95, 1.0]
curriculum_window: 100
