lr: 1.0e-4
v_lr: 3.0e-4
anneal_lr: false
adam_epsilon: 1.0e-8
num_steps: 128
gae: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 4
norm_adv: true
clip_coef: 0.2
clip_vloss: false
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
base_policy_path: "policies/base_policy_low_freq.pt"
use_base_policy_critic_structure: true
warmup_total_timesteps: 2500
warmup_seed: 0
alpha: 100.0
record_warmup_predicted_discounted_return: true
check_max_policy_ratios: true
check_ref_task_policy: false
ref_task_policy_path: "policies/task_policy_low_freq.pt"
save_db: true
save_db_ep_interval: 100
