lr: 1.0e-5
v_lr: 3.0e-4
anneal_lr: true
adam_epsilon: 1.0e-8
num_steps: 2048
gae: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 32
update_epochs: 10
norm_adv: true
clip_coef: 0.02
clip_vloss: false
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
base_policy_path: "policies/base_policy.pt"
use_base_policy_critic_structure: true
warmup_total_timesteps: 50000
warmup_seed: 0
alpha: 100.0
record_warmup_predicted_discounted_return: true
check_max_policy_ratios: true
