policy_lr: 2.0e-4
q_lr: 7.0e-4
adam_epsilon: 1.0e-8
gamma: 0.99
buffer_size: 1000000
batch_size: 512
burn_in: 5000
ent_coeff: 0.2
autotune: true
policy_freq: 2
targ_net_freq: 1
tau: 0.005
targ_ent_coeff: 0.0
per: true
per_alpha: 0.6
per_beta_start: 0.4
per_beta_end: 1.0
curriculum: true
curriculum_levels: [1, 2, 3, 4, 5]
curriculum_thresholds: [0.95, 0.95, 0.95, 0.95, 1.0]
curriculum_window: 100
