gym_id: "HalfCheetah-v4"
policy_lr: 3.0e-4
q_lr: 1.0e-3
adam_epsilon: 1.0e-8
seed: 0
total_timesteps: 100000
torch_deterministic: true
cuda: true
capture_video: true
video_ep_interval: 100
num_envs: 1
gamma: 0.99
buffer_size: 1000000
batch_size: 256
burn_in: 5000
ent_coef: 0.2
autotune: true
policy_freq: 2
targ_net_freq: 1
tau: 0.005
