program: ppo_discrete_action.py
name: sweepdemo
method: grid
metric:
  goal: maximize
  name: charts/episodic_return
parameters:
  train.target_kl:
    values: [null, 0.015]
  wandb.group:
    value: "test_sweep"

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
