name: rl-safety-filters

channels:
  - pytorch
  - nvidia/label/cuda-11.7.1
  - defaults
  - conda-forge

dependencies:
  - python = 3.10
  - pip

  # Optimization
  - cvxpy

  # Learning Basics
  - pytorch::pytorch >= 1.10.0
  - pytorch::torchvision
  - pytorch::pytorch-mutex = *=*cuda*
  - pip:
      - safety-gymnasium >= 0.1
  - tensorboard
  - wandb

  # Other dependencies
  - numpy
  # - moviepy
  # - pyyaml
  # - typer
  - seaborn
  - pandas
  - matplotlib
  # - typing-extensions

  # Device select
  - nvidia/label/cuda-11.7.1::cuda-toolkit = 11.7
